# Generated by Django 4.1.2 on 2022-10-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='Version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refbooks.version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='refbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refbooks.refbook'),
        ),
    ]
