# Generated by Django 4.1.2 on 2022-10-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0002_alter_element_version_alter_version_refbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='Version',
            new_name='version',
        ),
    ]
