# Generated by Django 4.1.2 on 2022-11-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0004_refbook_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='name',
            new_name='value',
        ),
    ]
